project: 
  type: book
  output-dir: _book
  
book:
  title: "TNW RDM 101"
  author: "Esther Plomp"
  date: last-modified 
  description: "TNW RDM 101" 
  
  page-footer:
    left: |
      <a href="https://estherplomp.github.io/TNW-RDM-101/">TNW RDM 101</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://estherplomp.github.io/TNW-RDM-101/
  repo-url: https://github.com/EstherPlomp/TNW-RDM-101/
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-Introduction.qmd
    - 02-Importance-of-RDM.qmd
    - 03-Essentials-for-Research-Data.qmd
    - 04-Assignment-Data-Flow-Map-1.qmd
    - 05-FAIR-principles.qmd
    - 06-Realising-FAIR-Organisation.qmd
    - 07-Realising-FAIR-Documentation.qmd
    - 08-Realising-FAIR-Publication.qmd
    - 09-Plan-for-RDM.qmd.qmd
    - 10-Wrap-up.qmd
    - 11-computing.qmd
    - 12-umassd-resources.qmd
#    - 13-smast-resources.qmd
#    - 14-other-faylab-resources.qmd  


# not sure what the following line does; those files are present
bibliography: [references.bib, book.bib]

